name: Build client

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build
        run: |
          cd client
          npm install
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: |
            client/build
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download client from artifact
        uses: actions/download-artifact@v4
        with:
          name: client-dist
          path: client/build
      - name: Display structure of downloaded files
        run: ls -R
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tomaso/dc:latest
          platforms: linux/amd64,linux/arm64
      - name: Kick update
        run: curl -v http://kouba.xyz:7927/update_app/display_case

# - uses: actions/download-artifact@master
#  with:
#    name: my-artifact
#    path: path/to/artifact
